### PR TITLE
[ci] Migrate to github actions

### PR DESCRIPTION
**Pull request by tobil4sk**
The following secret has to be set: `secrets.GHP_REMOTE`. Would you be able to configure this? @andyli 

According to Config.hx:
`// should be in the form of https://token@github.com/account/repo.git`

### CODE REVIEW

**Comment by kLabz** [comment]
I'll look into the missing secrets

**Comment by tobil4sk** [comment]
I think the token is meant to be for this account: https://github.com/haxe-ci

**Comment by kLabz** [comment]
I'm actually not sure we should be doing that; shouldn't we use a more conventional workflow and push to a dedicated GH Pages branch here?

**Comment by tobil4sk** [comment]
Yes, we have a gh-pages branch which @haxe-ci pushes to: https://github.com/HaxeFoundation/nekovm.org/tree/gh-pages

**Comment by kLabz** [comment]
I mean setting up https://github.com/peaceiris/actions-gh-pages or similar instead of `haxe deploy.hxml`

**Comment by tobil4sk** [comment]
Oh yeah, that looks promising. Looks like there's also: https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#configuring-the-configure-pages-action

**Comment by tobil4sk** [comment]
I've changed it to use the actions provided by github for deploying pages. I couldn't get it working on my github.io page due to the absolute path links but I've tested when running on a local server (though, GHP_ROOT has to be unset to avoid redirecting) and there the page displays fine.

**Pull request merged**
